### ISSUE TITLE
This is not an issues it is a question

### ISSUE THREAD

**Issue by GreenLeon23** [CardboardPowered/cardboard#167]
I was on curseforge's site and couldn't post comments (IDK why), is it possible to make something like this but reversed so like you can use mods on paper servers because I want origins mod but fabric server are not optimized so everything lags :(

**Comment by bonn2** [comment]
It might be possible, but it would be even more limited than Cardboard is, since paper frankly has much less freedom when it comes to modifying the game. Either way it is outside the scope of this project.
I would reccomend that if you are having perforamce issues running fabric to check out the performance section of [this list](https://gist.github.com/comp500/12417ee3685f6204362e933c9bcde603) of native fabric mods, rather than trying to run modifications on a different modloader than they were ment for.

**Comment by Jaqueka1432** [comment]
> 
> 
> Is it possible to make something like this but reversed so like you can use mods on paper servers because I want origins mod but fabric server are not optimized so everything lags :(

> 
> 
> It might be possible, but it would be even more limited than Cardboard already is.

If the server goes like crap, then I recommend installing performance-improving spigot plugins (like clearlag and others) and fabric mods (like lithium, phosphor and others) with cardboard - trust me.

I have a survival server with my friend and it went like crap at first, then i installed fabric on it and then the mods (lithium, phosphor) and it went like a 60% better.

I haven't tried cardboard yet but my guess with this is "If fabric with lithium and phosphor is good already, then cardboard which combines fabric with paper (which from what I've heard is excellent for performance) should be better, right?"

**Comment by bonn2** [comment]
Cardboard is not a performance plugin, it is a compatibility plugin. Paper is fast, but cardboard is not designed to implement the performance patches of it

**Comment by Jaqueka1432** [comment]
Oh
