### ISSUE TITLE
Cardboard crashes fabric server

### ISSUE THREAD

**Issue by OnlyDucks** [CardboardPowered/cardboard#216]
Just put cardboard in mods folder and ran fabric server, this happened

https://justpaste.it/5vaxu

paste it link cause too many letters

**Comment by UdonOli** [comment]
This issue is due to you using Cardboard in 1.17. Cardboard does **not** work with 1.17 (yet) and if you are trying to run a server with it it will crash. I am not looking to see what version you have, but if you aren't already, try to use the newest beta 1.16 version.

If that doesn't work, you will not be able to use Cardboard until a 1.17 version comes out.
